In [23]:
# Import libraries
import numpy as np

# Define a function
def analyze_vector_set(vectors):
    """
    Get a list of arrays and compute:
        1. Rank
        2. Nulity (#columns - rank)
    And check if the matrix is a base: R^m if rank == m
    """

    # Calculate the rank
    rank = np.linalg.matrix_rank(A)

    # Calculate the Nulity
    null = A.shape[1] - rank

    return (rank, null)


In [ ]:
 # Stacking 1D arrays
arr_1 = np.array([1, 0, 0])
arr_2 = np.array([0, 1, 0])
arr_3 = np.array([2, 3, 0])
A = np.column_stack((arr_1, arr_2, arr_3))

# Analyzing the matrix
rank, null = analyze_vector_set(A)

# check if the matrix is a base
if rank-null == 0:
    print("Matrix A:")
    print(A)
    print(f"\nMatrix A is a basis: dim = {A.shape[1]}")
else:
    print("Matrix A:")
    print(A)
    print(f"\nMatrix A is not a base, since Nulity != 0")



Matrix A:
[[1 0 2]
 [0 1 3]
 [0 0 0]]

Matrix A is not a base, since Nulity != 0
