In [ ]:
import numpy as np

def is_linear_independent():
    """
    check if the vectors are Linearly Dependent or Linearly Independent
    """
    # 1. Define vectors u, v, w
    u = np.array([1, 0, 0])
    v = np.array([0, 1, 0])
    w = np.array([2, 3, 0])
    stacked_1d = np.column_stack((u, v, w))

    # 2. Find the matrix's Rank
    rank = np.linalg.matrix_rank(stacked_1d)   

    # 3. Print results:
    print("Column vectors: u, v, w")
    print(stacked_1d)
    if rank == stacked_1d.shape[1]:
        print("\nThe vectors are linearly independent, since rank = number of columns")
        print(f"\nRank = {rank} | Number of columns = {stacked_1d.shape[1]}")
    else:
        print("\nThe vectors are linerly dependent, since rank < number of columns")
        print(f"\nRank = {rank} | Number of columns = {stacked_1d.shape[1]}")

In [7]:
is_linear_independent()

Column vectors: u, v, w
[[1 0 2]
 [0 1 3]
 [0 0 0]]

The vectors are linerly dependent, since rank < number of columns

Rank = 2 | Number of columns = 3
